"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "../../Pages/Layout/SideBar/SideBar";
import SignIn from "./Sign-In/page";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

//  const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [auth, SetAuth] = useState<boolean>(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* <div className="grid gap-0 grid-cols-[auto,1fr,1fr]">
          <SideBar />
          {children}
        </div> */}
      </body>
    </html>
  );
}
